version: "3.8"

services:
  db:
    image: mongo
    volumes:
      - .docker/data/db:/data/db
    ports: 
      - "27017:27017" 
    volumes:
      - .docker/data/db:/data/db  
    restart: unless-stopped
  
  redis:
    image: redis:5-alpine
    # volumes:
    #   - .docker/data/redis:/data
    ports: 
      - "6379:6379" 
    restart: unless-stopped